# Generated by Django 5.2.6 on 2025-10-03 13:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverificationtoken',
            options={'ordering': ['-created_at'], 'verbose_name': 'Email Verification Token', 'verbose_name_plural': 'Email Verification Tokens'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address where token was created', null=True, verbose_name='IP Address'),
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='used_at',
            field=models.DateTimeField(blank=True, help_text='When this token was used', null=True, verbose_name='Used at'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='User biography', max_length=500, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, help_text='User birth date', null=True, verbose_name='Birth Date'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When this profile was created', verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='User phone number', max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this profile was last updated', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this token was created', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='expires_at',
            field=models.DateTimeField(help_text='When this token expires', verbose_name='Expires at'),
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Unique verification token', unique=True, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='used',
            field=models.BooleanField(default=False, help_text='Whether this token has been used', verbose_name='Used'),
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='user',
            field=models.ForeignKey(help_text='The user this verification token belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Whether the user has verified their email address', verbose_name='Email Verified'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, help_text='When the email was verified', null=True, verbose_name='Email Verified At'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(help_text='The user this profile belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='emailverificationtoken',
            index=models.Index(fields=['user', 'used', 'expires_at'], name='authenticat_user_id_ba52b5_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverificationtoken',
            index=models.Index(fields=['token'], name='authenticat_token_e79b2f_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverificationtoken',
            index=models.Index(fields=['expires_at'], name='authenticat_expires_ae4371_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['email_verified'], name='authenticat_email_v_b97d98_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['email_verified_at'], name='authenticat_email_v_f9fe18_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['created_at'], name='authenticat_created_ddfd1f_idx'),
        ),
    ]
